// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRUgwnifqrCDuX14SXcyKPDqtpJez49aM',
    appId: '1:446134580895:web:3dfe81607be9fdc76094aa',
    messagingSenderId: '446134580895',
    projectId: 'ast-app-55235',
    authDomain: 'ast-app-55235.firebaseapp.com',
    storageBucket: 'ast-app-55235.firebasestorage.app',
    measurementId: 'G-RTJ21318LP',
  );

  // TODO: Reemplazar con la configuración real de Firebase

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6OUBnIPHogm5IUVr16x2dn8dnWmZ7bw',
    appId: '1:446134580895:android:8e91b45c57aac2066094aa',
    messagingSenderId: '446134580895',
    projectId: 'ast-app-55235',
    storageBucket: 'ast-app-55235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3m9h5PWGOh8Ff95EObFvXY6Bp8LtTGTA',
    appId: '1:446134580895:ios:ff516eb29f1c72106094aa',
    messagingSenderId: '446134580895',
    projectId: 'ast-app-55235',
    storageBucket: 'ast-app-55235.firebasestorage.app',
    iosBundleId: 'com.example.astMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3m9h5PWGOh8Ff95EObFvXY6Bp8LtTGTA',
    appId: '1:446134580895:ios:ff516eb29f1c72106094aa',
    messagingSenderId: '446134580895',
    projectId: 'ast-app-55235',
    storageBucket: 'ast-app-55235.firebasestorage.app',
    iosBundleId: 'com.example.astMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRUgwnifqrCDuX14SXcyKPDqtpJez49aM',
    appId: '1:446134580895:web:6691d55e0c73ba086094aa',
    messagingSenderId: '446134580895',
    projectId: 'ast-app-55235',
    authDomain: 'ast-app-55235.firebaseapp.com',
    storageBucket: 'ast-app-55235.firebasestorage.app',
    measurementId: 'G-8RMQBLNW3P',
  );

}